var GAME_LEVELS = [
  ["                                                                 x              ",
   "                                                                 x              ",
   "                                                                 x              ",
   "                                                       o         x              ",
   "                                                    o            x              ",
   "                                                    o            x              ",
   "                                                    o            xxxxx          ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                  o       xvx           ",
   "                       o o                                             xxx  xx  ",
   "  xx                                      o o                          x!x   x  ",
   "  x                  xxxxxxx                     xxxxxxxx              xvx   x  ",
   "  x                                      xxxxx   xxxxxxxx                  o x  ",
   "  x                     o         o              xxxxxxxx                    x  ",
   "  x  @                  |            x=         =xxxxxxxx                    x  ",
   "  xxxxxxxxxxx   xxxxxxxxxxxxxxxx  x  xxxxxxxxxxxxxxxxxxxx     xxxxxx  xxxxxxxxxx",
   "            x!!!x              x     x                  x     x                 ",
   "            x!!!x              x!!!!!x                  x!!!!!x                 ",
   "            xxxxx              x!!!!!x                  x!!!!!x                 ",
   "                               xxxxxxx                  xxxxxxx                 ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                       xxxxx                      ",
   "                                                                                       x!!!x                      ",
   "                                                                                       x!!vx                      ",
   "                                        xx      xx                                     xv  x                      ",
   "                                       xxxx    xxxx                                                               ",
   "                                        xx|    |xx                                           o o                  ",
   "                                                                                                                  ",
   "                                                                                   x        xxxx                  ",
   "                                            xx        o                            x o         x       o          ",
   "                                                                                   x           x       o          ",
   "                                                     xxx                           xxxxx       x       o          ",
   "                                        x   oo   x                                 x         o x                  ",
   "                                         x      x            o o o                 x           x                  ",
   "                                          xxxxxx                                   x        xxxx                  ",
   "                                                          xxxxxxxxxxx   x          x o         x                  ",
   "                                                                    x   x!!!!!!!!!!x           x                  ",
   "                                                                    x o x!!!!!!!!!!xxxxx       x    xxxxxxxx      ",
   "                                                  xxxxx    o  o     x   x!!!!!!!!!!x           x                  ",
   "                          o   xxx   xxx                             x   x!!!!!!!!!!x        o  x                  ",
   "                 o              x   x                     xxxxxx    x=  xxxxxxxxxxxx           x                  ",
   "              xxx o     xxxx    x o x                               x     |         o o     xxxx                  ",
   "     @        x  x             x=    x                xxxxx         x                          x                  ",
   "    xxxx      x   x             x   x                x              x               xxxx       x                  ",
   "    x  x      x    xxxxx      xxx o xx!!!!!!!!!xxx   x              x     o                    x                  ",
   "!!!!x  x!!!!!!x        x!!!!!!xx     xxxxxxxxxxx     x!!!!!!!!!     x     o                    x                  ",
   "!!!!x  x!!!!!!x        x!!!!!xx                      x!!!!!!!xx     xxxxxxxxxxxxxxxx  o o  xxxxx                  ",
   "!!!!x  x!!!!!!x        x!!!!!x=    o                xxx!!!!!!xx                    xx     xx                      ",
   "!!!!x  x!!!!!!x        x!!!!!x                    xx!!!!!!xx                       xxxx!xxxx                      ",
   "!!!!x  x!!!!!!x        x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx                                                      ",
   "!!!!x  x!!!!!!x        x!!!!!!xxx   xxx!!!!!!!!!!!!!!!!!xx                                                        ",
   "!!!!x  x!!!!!!x        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                    oo                                                                                         ",
   "                                                                                                                          ooooo ooooo o   o    ",
   "                                                                                                                          o       o   oo  o    ",
   "                                  xxxxxxxx                                                                                oooo    o   o o o    ",
   "                                  x   |           x!!!!x                                                                  o       o   o  oo    ",
   "                                  x            xxxxxxxxxxxx                                                            @  o     ooooo o   o    ",
   "                                  x                |   x  xxxxxx            x!!!!!!!!!xxxxx=    x=     x=     x=     xxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                  xo                   x       x            xxvxxxvxxx          x      x      x      x                         ",
   "                                  xxxxxxxx             x       x=  o o     =x                   x      x      x      x                         ",
   "                                  x   |               ox       x            x               o   x   o  x   o  x   o  x                         ",
   "                                  x            xxxxxxxxx       x     xxxxxxxx   oo       xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                         ",
   "                                  x                |   x       x=          =x          xxx |          |                                        ",
   "                                  xo                   x       x    o o     x                                                                  ",
   "                                  xxxxxxxx             x       x            x                                                                  ",
   "                                      |  x            ox       xxxxxxxx     xxxxxxxxxx                                                         ",
   "                                         x     xxxxxxxxx       x=          =x!v!!!v!!!  oo   oo                                                ",
   "                                               x               x     o o    x                                                                  ",
   "                                        o      x               x            x           xx!!!xx    oo   oo                                     ",
   "                        oo   xxxxxxxxxxxxxxx   x               x      xxxxxxx             xxx                                                  ",
   "                                                               x            x              |                                                   ",
   "                o o    xxxx                                    x            x                      xx!!!xx                                     ",
   "                                                               x      o                              xxx                                       ",
   "  xxxx         xxxxx                                           x          o             oo   oo                                                ",
   "  x                                                            xxxxx          o   o                                                            ",
   "  x                            oo                                  xxxxx                xx!!!xx                                                ",
   "  x    !xx!xx!xx!xx!xx!xx!xx                                           xxxxx              xxx                                                  ",
   "  x    xxxxxxxxxxxxxxx|xxxxx  xxxx    oo                                    xxxxxxxxxx                                                         ",
   "  x    xxxxxxx|xxxxxxx xxxxx                                                                                                                   ",
   "  x    xxx|xxx xxxxxxx xxxxx         xxxx                                                                                                      ",
   "  x    xxx xxx xxx|xxx xxxxx                                                                                                                   ",
   "  x                              xxx                                                                                                           ",        
   "  x                            xx                                                                                                              ",         
   "  x                           x                                                                                                                ",           
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                ",  
   "                                                                                                                                               "]


];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;